name: Auto-format (Nix + Lua)

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - name: Apply formatting
        run: |
          nix run nixpkgs#alejandra -- -q .
          nix run nixpkgs#stylua -- .

      - name: Ensure no formatting changes are needed
        run: |
          git diff --exit-code

